const { Pool } = require('pg');
require('dotenv').config({ path: require('path').resolve(__dirname, '../../../../.env') });

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const facilities = [
    {
        id: 'fac_001',
        name: 'Hôpital Général de Douala',
        type: 'hospital',
        city: 'Douala',
        district: 'Bali',
        address: 'Rue Manga Bell, Bali, Douala',
        phone: '+237 233 425 200',
        latitude: 4.0611,
        longitude: 9.7479,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '07:00-20:00',
        hours_sunday: '07:00-20:00',
        is_24h: true,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: true,
        services: ['emergency', 'surgery', 'maternity', 'pediatrics', 'radiology'],
    },
    {
        id: 'fac_002',
        name: 'Hôpital Laquintinie',
        type: 'hospital',
        city: 'Douala',
        district: 'Akwa',
        address: 'Avenue Laquintinie, Akwa, Douala',
        phone: '+237 233 423 140',
        latitude: 4.0511,
        longitude: 9.7079,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '07:00-20:00',
        hours_sunday: '07:00-20:00',
        is_24h: true,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: false,
        payment_insurance: true,
        services: ['emergency', 'surgery', 'consultation', 'maternity'],
    },
    {
        id: 'fac_003',
        name: 'Hôpital de District Bonassama',
        type: 'hospital',
        city: 'Douala',
        district: 'Bonassama',
        address: 'Bonassama, Douala',
        phone: '+237 233 412 300',
        latitude: 4.0811,
        longitude: 9.6979,
        hours_weekdays: '07:00-18:00',
        hours_saturday: '07:00-14:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: false,
        payment_insurance: false,
        services: ['consultation', 'emergency', 'maternity'],
    },
    {
        id: 'fac_004',
        name: 'Clinique La Grâce',
        type: 'clinic',
        city: 'Douala',
        district: 'Akwa',
        address: 'Rue Joffre, Akwa, Douala',
        phone: '+237 699 000 001',
        latitude: 4.0511,
        longitude: 9.7679,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '08:00-17:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['consultation', 'emergency', 'maternity', 'pediatrics'],
    },
    {
        id: 'fac_005',
        name: 'Clinique Pasteur',
        type: 'clinic',
        city: 'Douala',
        district: 'Bonanjo',
        address: 'Rue Pasteur, Bonanjo, Douala',
        phone: '+237 699 000 002',
        latitude: 4.0451,
        longitude: 9.6979,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '08:00-17:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: false,
        payment_insurance: true,
        services: ['consultation', 'surgery', 'radiology'],
    },
    {
        id: 'fac_006',
        name: 'Clinique Fouda',
        type: 'clinic',
        city: 'Douala',
        district: 'Bonapriso',
        address: 'Bonapriso, Douala',
        phone: '+237 699 000 003',
        latitude: 4.0351,
        longitude: 9.7079,
        hours_weekdays: '07:00-19:00',
        hours_saturday: '08:00-14:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['consultation', 'pediatrics', 'gynecology'],
    },
    {
        id: 'fac_007',
        name: 'Clinique Bethesda',
        type: 'clinic',
        city: 'Douala',
        district: 'Ndokotti',
        address: 'Ndokotti, Douala',
        phone: '+237 699 000 004',
        latitude: 4.0711,
        longitude: 9.7379,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '08:00-17:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['consultation', 'maternity', 'pediatrics'],
    },
    {
        id: 'fac_008',
        name: 'Pharmacie du Wouri',
        type: 'pharmacy',
        city: 'Douala',
        district: 'Akwa',
        address: 'Boulevard de la Liberté, Akwa, Douala',
        phone: '+237 699 000 005',
        latitude: 4.0521,
        longitude: 9.7089,
        hours_weekdays: '08:00-21:00',
        hours_saturday: '08:00-21:00',
        hours_sunday: '09:00-18:00',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['pharmacy', 'parapharmacy'],
    },
    {
        id: 'fac_009',
        name: 'Pharmacie Centrale',
        type: 'pharmacy',
        city: 'Douala',
        district: 'Bonanjo',
        address: 'Rue Joss, Bonanjo, Douala',
        phone: '+237 699 000 006',
        latitude: 4.0461,
        longitude: 9.6989,
        hours_weekdays: '08:00-21:00',
        hours_saturday: '08:00-20:00',
        hours_sunday: '10:00-18:00',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: false,
        payment_insurance: false,
        services: ['pharmacy'],
    },
    {
        id: 'fac_010',
        name: 'Pharmacie de la Paix',
        type: 'pharmacy',
        city: 'Douala',
        district: 'Makepe',
        address: 'Makepe, Douala',
        phone: '+237 699 000 007',
        latitude: 4.0811,
        longitude: 9.7579,
        hours_weekdays: '08:00-21:00',
        hours_saturday: '08:00-20:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['pharmacy', 'parapharmacy'],
    },
    {
        id: 'fac_011',
        name: 'Pharmacie Bonne Santé',
        type: 'pharmacy',
        city: 'Douala',
        district: 'Deido',
        address: 'Deido, Douala',
        phone: '+237 699 000 008',
        latitude: 4.0611,
        longitude: 9.7179,
        hours_weekdays: '08:00-21:00',
        hours_saturday: '08:00-20:00',
        hours_sunday: '10:00-18:00',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['pharmacy'],
    },
    {
        id: 'fac_012',
        name: 'Pharmacie de Garde Nkongmondo',
        type: 'pharmacy',
        city: 'Douala',
        district: 'Nkongmondo',
        address: 'Nkongmondo, Douala',
        phone: '+237 699 000 009',
        latitude: 4.0711,
        longitude: 9.7279,
        hours_weekdays: '08:00-22:00',
        hours_saturday: '08:00-22:00',
        hours_sunday: '08:00-22:00',
        is_24h: false,
        is_on_duty: true,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['pharmacy'],
    },
    {
        id: 'fac_013',
        name: 'Laboratoire LANACOME',
        type: 'laboratory',
        city: 'Douala',
        district: 'Akwa',
        address: 'Akwa, Douala',
        phone: '+237 699 000 010',
        latitude: 4.0531,
        longitude: 9.7089,
        hours_weekdays: '07:00-17:00',
        hours_saturday: '07:00-13:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: false,
        payment_insurance: true,
        services: ['blood_test', 'urine_test', 'microbiology', 'serology'],
    },
    {
        id: 'fac_014',
        name: 'Laboratoire Cerba',
        type: 'laboratory',
        city: 'Douala',
        district: 'Bonanjo',
        address: 'Bonanjo, Douala',
        phone: '+237 699 000 011',
        latitude: 4.0471,
        longitude: 9.6999,
        hours_weekdays: '07:00-17:00',
        hours_saturday: '07:00-13:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: true,
        services: ['blood_test', 'urine_test', 'radiology', 'serology'],
    },
    {
        id: 'fac_015',
        name: 'CSI de Bépanda',
        type: 'health_center',
        city: 'Douala',
        district: 'Bépanda',
        address: 'Bépanda, Douala',
        phone: '+237 699 000 012',
        latitude: 4.0751,
        longitude: 9.7479,
        hours_weekdays: '07:00-15:00',
        hours_saturday: '07:00-13:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: false,
        payment_insurance: false,
        services: ['consultation', 'vaccination', 'family_planning'],
    },
    {
        id: 'fac_016',
        name: 'Hôpital Central de Yaoundé',
        type: 'hospital',
        city: 'Yaoundé',
        district: 'Centre',
        address: 'Rue Henri Dunant, Centre, Yaoundé',
        phone: '+237 222 230 012',
        latitude: 3.8661,
        longitude: 11.5161,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '07:00-20:00',
        hours_sunday: '07:00-20:00',
        is_24h: true,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: true,
        services: ['emergency', 'surgery', 'maternity', 'pediatrics', 'radiology'],
    },
    {
        id: 'fac_017',
        name: "Clinique de l'Aéroport",
        type: 'clinic',
        city: 'Yaoundé',
        district: 'Nsimeyong',
        address: 'Nsimeyong, Yaoundé',
        phone: '+237 699 000 013',
        latitude: 3.8361,
        longitude: 11.5061,
        hours_weekdays: '07:00-20:00',
        hours_saturday: '08:00-17:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['consultation', 'surgery', 'radiology'],
    },
    {
        id: 'fac_018',
        name: 'Pharmacie du Rond-Point',
        type: 'pharmacy',
        city: 'Yaoundé',
        district: 'Bastos',
        address: 'Bastos, Yaoundé',
        phone: '+237 699 000 014',
        latitude: 3.8761,
        longitude: 11.5261,
        hours_weekdays: '08:00-21:00',
        hours_saturday: '08:00-21:00',
        hours_sunday: '10:00-18:00',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: true,
        payment_orange_money: true,
        payment_insurance: false,
        services: ['pharmacy', 'parapharmacy'],
    },
    {
        id: 'fac_019',
        name: 'Laboratoire LABOGUI',
        type: 'laboratory',
        city: 'Yaoundé',
        district: 'Centre',
        address: 'Centre, Yaoundé',
        phone: '+237 699 000 015',
        latitude: 3.8661,
        longitude: 11.5061,
        hours_weekdays: '07:00-17:00',
        hours_saturday: '07:00-13:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: true,
        payment_insurance: true,
        services: ['blood_test', 'urine_test', 'microbiology'],
    },
    {
        id: 'fac_020',
        name: 'CSI de Nkolbisson',
        type: 'health_center',
        city: 'Yaoundé',
        district: 'Nkolbisson',
        address: 'Nkolbisson, Yaoundé',
        phone: '+237 699 000 016',
        latitude: 3.8461,
        longitude: 11.4861,
        hours_weekdays: '07:00-15:00',
        hours_saturday: '07:00-13:00',
        hours_sunday: 'Emergency only',
        is_24h: false,
        is_on_duty: false,
        payment_cash: true,
        payment_mtn_momo: false,
        payment_orange_money: false,
        payment_insurance: false,
        services: ['consultation', 'vaccination', 'family_planning'],
    },
];

async function seed() {
    const client = await pool.connect();
    try
    {
        await client.query('BEGIN');
        for (const f of facilities) {
            await client.query(
                `INSERT INTO facilities (
                    id, name, type, city, district, address, phone, latitude, longitude,
                    hours_weekdays, hours_saturday, hours_sunday, is_24h, is_on_duty,
                    payment_cash, payment_mtn_momo, payment_orange_money, payment_insurance
                ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) ON CONFLICT (id) 
                DO NOTHING`,
                [
                    f.id, f.name, f.type, f.city, f.district, f.address, f.phone,
                    f.latitude, f.longitude, f.hours_weekdays, f.hours_saturday,
                    f.hours_sunday, f.is_24h, f.is_on_duty, f.payment_cash,
                    f.payment_mtn_momo, f.payment_orange_money, f.payment_insurance,
                ]
            );
            for (const service of f.services) {
                await client.query(
                    `INSERT INTO facility_services (facility_id, service) VALUES ($1, $2)`,
                    [f.id, service]
                );
            }
        }
        await client.query('COMMIT');
        console.log('Seed completed - 20 facilities inserted.');
    } catch (error) {
        await client.query('ROLLBACK');
        console.error('Seed failed:', err.message);
    } finally {
        client.release();
        await pool.end();
    }
}

seed();